# Generated by Django 4.1 on 2023-01-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_blog2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_text',
            new_name='blog_text_2',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='title_2',
        ),
        migrations.RenameField(
            model_name='blog2',
            old_name='title',
            new_name='title_1',
        ),
    ]
