# Generated by Django 4.1 on 2023-01-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_remove_blog_created_at_remove_blog_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='main_image',
        ),
    ]
