# Generated by Django 4.1 on 2023-01-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_remove_blog_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog2',
            name='date_1',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
